version: '3.8'

services:
  # Nombre de nuestro servicio
  esports-prediction-service:
    # Build indica que debe usar el Dockerfile que está en esta misma carpeta (.)
    build: .
    # Nombre que tendrá el contenedor al ejecutarse
    container_name: esports_serving_container
    # Mapeo de Volúmenes: Sincroniza tus carpetas locales con las del contenedor
    # Esto es vital en MLOps para que el modelo pueda leer datos nuevos sin reconstruir la imagen
    volumes:
      - .:/app
    # Mapeo de Puertos: Puerto de tu PC : Puerto del Contenedor
    ports:
      - "5000:5000"
    # Reinicio automático si algo falla
    restart: "no"
