{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "source": [
        "%%writefile Dockerfile\n",
        "# Usamos una imagen ligera de Python\n",
        "FROM python:3.9-slim\n",
        "\n",
        "# Directorio de trabajo\n",
        "WORKDIR /app\n",
        "\n",
        "# Copiar requerimientos e instalar\n",
        "COPY requirements.txt .\n",
        "RUN pip install --no-cache-dir -r requirements.txt\n",
        "\n",
        "# Copiar el resto del proyecto\n",
        "COPY . .\n",
        "\n",
        "# Comando para ejecutar el servicio\n",
        "CMD [\"python\", \"src/predict_service.py\"]"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "YjsIirzmfu2p",
        "outputId": "c8041b87-4547-47e9-da53-481428ad0700"
      },
      "execution_count": 2,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Writing Dockerfile\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "%%writefile requirements.txt\n",
        "pandas\n",
        "numpy\n",
        "scikit-learn\n",
        "skrebate\n",
        "joblib"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "nGWMQM_agiwe",
        "outputId": "6054cd10-3052-4331-dc3d-82c814e08d90"
      },
      "execution_count": 3,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Writing requirements.txt\n"
          ]
        }
      ]
    }
  ]
}